name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
    # https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
jobs:

  build:

    runs-on: ubuntu-latest

    # https://github.com/hadolint/hadolint
    steps:
    - uses: actions/checkout@v2
    - name: Lint the Dockerfile
      run: docker run --rm -i hadolint/hadolint < Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
